### ISSUE TITLE
The troubling Situation!

### ISSUE THREAD

**Issue by starkblaze01** [anshumanv/vueman.ga#33]
Things are not working out sergeant.
We couldn't access `vueman.ga`.
Seems like some enemies have taken over this domain name. We need to get it back immediately.
![Screenshot 2019-12-18 at 9 23 48 AM](https://user-images.githubusercontent.com/22374162/71054491-36f46580-2178-11ea-822d-bad9ec72d56c.png)

**Comment by anshumanv** [comment]
Thanks for the report, I'm aware that the domain has expired. Let's get it back sometime.

Meanwhile - https://vuemanga.netlify.com/
